(do (def e (enum-init { "selected" 1 "options" (:hello :world :man) })) true)
(= (enum-selected e) :world)
(= (enum-index e) 1)
(do (def e-mut (atom e)) true)
(do (enum-set-index e-mut 0) true)
(= (enum-selected @e-mut) :hello)
(= (enum-index @e-mut) 0)
(do (enum-set-selected e-mut :world) true)
(= (enum-selected @e-mut) :world)
(= (enum-index @e-mut) 1)
