(do (def e (enum-init { "selected" 1 "options" (:hello :world :man) })) true)
(= (enum-selected e) :world)
(= (enum-index e) 1)
(do (enum-set-index e 0) true)
(= (enum-selected e) :hello)
(= (enum-index e) 0)
(do (enum-set-selected e :world) true)
(= (enum-selected e) :world)
(= (enum-index e) 1)
